apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ul1pm7r8u-nodejs 
  janus-idp.io/tekton: ul1pm7r8u-nodejs
  backstage.io/kubernetes-id: ul1pm7r8u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ul1pm7r8u-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  