apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ul1pm7r8u-nodejs-gitops
  description: This is GitOps manifest for ul1pm7r8u-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ul1pm7r8u-nodejs
    janus-idp.io/tekton: ul1pm7r8u-nodejs 
    backstage.io/kubernetes-id: ul1pm7r8u-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ul1pm7r8u-nodejs
