apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ul1pm7r8u-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:0b95b3fe66f53a28e62543621a5d948777ba35f0@sha256:5e4ed04479e2300ac17ac0197ad42040e280e5ef20a1b4587dc159b5c394f6cf
          name: container-image
